In [10]:
import numpy as np
import copy

In [1]:
# Arithmatic operation 

In [19]:
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])

arr= arr1+arr2
print(arr)

# element number should be same 

[ 7  9 11 13 15]


In [21]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [22]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [23]:
arr1//arr2

array([0, 0, 0, 0, 0])

In [ ]:
# Broadcasting single value har elment pe add ya koi operation karna chhate ho toh broadcasting ka jaroorat padegi 

In [27]:
l1= [1,2,4,5]
a1= np.array(l1)
print(a1)
a2= a1+10
print(a2)

[1 2 4 5]
[11 12 14 15]


In [28]:
# similar broadcasting and arithmatic operation is done in matrix as well 

In [31]:
a=np.array([[1,2],[3,4],[5,6]])
b= np.array([[7,8],[9,10],[11,12]])
c= a*b
print(c)


[[ 7 16]
 [27 40]
 [55 72]]


In [35]:
arr1=np.array([1,2,3,4,5,6])
slice= arr1[::-1]
print(slice)
slice[0]=20
print(slice)
print(arr1)


[6 5 4 3 2 1]
[20  5  4  3  2  1]
[ 1  2  3  4  5 20]


In [36]:
arr1=np.array([1,2,3,4,5,6])
slice= arr1[::-1]
print(slice)
slice= slice*10
print(slice)
print(arr1)


[6 5 4 3 2 1]
[60 50 40 30 20 10]
[1 2 3 4 5 6]


In [42]:
arr1=np.array([1,2,3])
arr2=copy.deepcopy(arr1)
arr2[0]=12
print(arr1)
print(arr2)

[1 2 3]
[12  2  3]


In [ ]:
# matrix operation 

In [12]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[2,3],[4,5]])


In [14]:
c= a @ b  #matrix multiplication 
#or 
np.dot(a,b)

array([[10, 13],
       [22, 29],
       [34, 45]])

In [15]:
# Transpose of a matix 
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
# Stacking Array

In [17]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])

# vertical stack 
c= np.vstack((a,b))   #input should give in one positional argument that is touple 
print(c)

[[1 2 3 4]
 [3 4 5 6]]


In [20]:
# horizontal stack in one single array other array also appends and resultant is ssingle array 
c= np.hstack((a,b))
print(c)

[1 2 3 4 3 4 5 6]


In [21]:
# column stack 
c= np.column_stack((a,b))  # in matrix all the array act as a column 
print(c)

[[1 3]
 [2 4]
 [3 5]
 [4 6]]
