In [3]:
import numpy as np

In [4]:
arr= np.array([1,2,3,4])
# arr is array 

In [5]:
arr=[1,2,3,4]
# arr is list 

In [8]:
arr1= np.array([1,2.3,4,"Hello"])
print(arr1)
# numpy will convert everything into string because array can have a single datatype 

['1' '2.3' '4' 'Hello']


In [9]:
list1= [1,2,3,"hello"]
print(list1)

[1, 2, 3, 'hello']


In [12]:
np.array(list1)


array(['1', '2', '3', 'hello'], dtype='<U21')

In [16]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)
# 2d list 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [18]:
arr= np.array(l)
print(arr)
# 2d array 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Array generation functions 

In [19]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr= np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [31]:
# generating array of 0's 
arr= np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [32]:
# generating 2d array of zeros 
arr= np.zeros((5,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [33]:
arr= np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [7]:
arr= np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# linspace returns the evenly space numbers between range 
arr = np.linspace(1,10,2)
print(arr)

[ 1. 10.]


In [39]:
arr = np.linspace(1,10,4)
print(arr)
# sare numbers ke bech me same space hoga 

[ 1.  4.  7. 10.]


In [46]:
# random generation functions 
# import random 
# arr= np.random.randint(1,10)
# print(arr)
# select one number between 1 and 10 inclusive 

arr= np.random.rand(10)
print(arr)
# generate random 10 float between 0 to 1 


[0.71793283 0.03013278 0.92160745 0.89835711 0.74448106 0.96687406
 0.72886387 0.96366093 0.41673573 0.50340365]


In [1017]:
arr= np.random.randint(6)
print(arr)
#  generate  random integer between 0 to 5 

3


In [1020]:
arr= np.random.randint(1,10,5)
print(arr)
# pick random 5 interget between 1 and 10 

[9 2 4 1 4]


In [ ]:
# Array attributes 

In [8]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(arr.size)

9


In [10]:
print(arr.shape)

(3, 3)


In [11]:
print(arr.dtype)

int64


In [ ]:
# Array methods 

In [12]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1029]:
print(arr.min())

1


In [1030]:
print(arr.max())

9


In [1031]:
print(arr.sum())

45


In [1035]:
# find the sum of array along vertical and horizontal 
sumofcolumns= np.sum(arr,axis=0)
print(sumofcolumns)
# axis =0 gives the sum of all the columns 



[12 15 18]


In [1036]:
sumofrows= np.sum(arr,axis=1)
print(sumofrows)
# gives the sum of all the rows 


[ 6 15 24]


In [1037]:
print(arr.mean())


5.0


In [13]:
print(arr.std())

2.581988897471611


In [14]:
print(arr.argmax())
# print the index of the max element 

8


In [15]:
print(arr.argmin())
# print the index of the min element in the array

0


In [ ]:
# Reshaping and Resizing 

In [16]:
arr= np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [17]:
# now reshape the array 
arr= arr.reshape(6,5)
print(arr)
# here m*n should be the total number of elements we have in the array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
