In [2]:
import numpy as np


In [3]:
arr= np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [4]:
print(arr[4]);

15


In [8]:
arrslice = arr[::-1];
print(arrslice)
arrslice[2]=50; # original array is changed because it is referencing to same array shallow copy just create another view of same memory 
print(arr);


[20 19 18 17 16 15 14 13 12 11]
[11 12 13 14 15 16 17 50 19 20]


In [26]:
# Numpy indexing and slicing og 2d matrix 
arr= np.arange(1,31).reshape(6,5);
print(arr);
print("\n");
print(arr[0,0]); #accessing the element in the 
print(arr[5,4]);

# slicing in one row 
# arr1= arr[0][0:4:1];
# arr2= arr[5][::-1];
# print(arr1);
# print(arr2);

# slicing for multiple rows 
arr3= arr[0:2, 1:3];
print(arr3);

arr4=arr[1:5, 1:4];  #remove all the border of a matrix 
print(arr4);

arr5= arr[:,2:3]; #here we are saying all rows and slice colum 3 to 3 means 3 so we get a matrix 
print(arr5)

arr5= arr[:,2]; # But here we are saying all rows and column 2 so here we get a oned array 
print(arr5)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


1
30
[[2 3]
 [7 8]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]
 [28]]


In [27]:
# Boolean Indexing 

In [36]:
arr= np.arange(11,21);
print(arr)

bool_index= arr%2 == 0;
print(bool_index);  # this array is a bollean array stroing the result of operation on each element 
even_array=arr[bool_index]; #now use boolean array as index and numpy store only the element having true value in boolean array 
print(even_array)

[11 12 13 14 15 16 17 18 19 20]
[False  True False  True False  True False  True False  True]
[12 14 16 18 20]
